# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-08 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_title',
            new_name='title',
        ),
    ]
