# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-09 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_profile_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('hours', models.IntegerField()),
                ('trainee_cnt', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timeline',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer.Profile'),
        ),
    ]
