# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_auto_20180918_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
