# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(default='kalpeshtawde@outlook.com', max_length=200),
            preserve_default=False,
        ),
    ]
