# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0008_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='+1 123 574 5621', max_length=20),
            preserve_default=False,
        ),
    ]
