# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0009_auto_20180918_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='214, 8th Street, Miami Beach, Miami, FL 102-253', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='website',
            field=models.CharField(default='www.mikewillmade.it', max_length=200),
            preserve_default=False,
        ),
    ]
