# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0011_auto_20180918_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='technology',
            field=models.CharField(default='Python', max_length=500),
            preserve_default=False,
        ),
    ]
