# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0013_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
