# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-13 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0015_auto_20181001_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.FileField(default='media/default_user.png', null=True, upload_to=''),
        ),
    ]
