# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0018_auto_20181020_2309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
    ]
