# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainer', '0021_auto_20181024_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='profile',
        ),
        migrations.AddField(
            model_name='timeline',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
