# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0023_auto_20181024_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='to_date',
        ),
    ]
