# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0026_experience_from_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='to_year',
            field=models.IntegerField(default=2018, max_length=4),
            preserve_default=False,
        ),
    ]
