# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0027_experience_to_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='from_month',
            field=models.CharField(default='Nov', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='to_month',
            field=models.CharField(default='Nov', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experience',
            name='from_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='to_year',
            field=models.IntegerField(),
        ),
    ]
