# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-04 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0030_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
