# Generated by Django 2.1.3 on 2019-02-23 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0033_auto_20190217_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='id',
        ),
        migrations.AlterField(
            model_name='availability',
            name='locations',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='availability',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
