# Generated by Django 2.1.3 on 2019-02-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0035_auto_20190223_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='activation_string',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
